version: '3.8'

services:
  # Flask + Redis часть
  web:
    build: ./flask-app
    ports:
      - "8000:5000"
    networks:
      - monitoring_network
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    networks:
      - monitoring_network

  # Prometheus + Grafana часть
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command: ['--config.file=/etc/prometheus/prometheus.yml']
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - monitoring_network
    depends_on:
      - blackbox
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      - monitoring_network
    depends_on:
      - prometheus

  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    ports:
      - "9115:9115"
    networks:
      - monitoring_network

volumes:
  prom_data:

networks:
  monitoring_network:
    driver: bridge
